#pragma once
#include "headerdata.h"
#include "exprtk.hpp"
#include "channelfunction.h"

class mixinfunction : public exprtk::ivararg_function<double>
{
public:
    virtual inline double operator() (const std::vector<double>& params)
    {
        double t = params[0];
        double T = params[1];
        double value = 0;
        double max = 0;
        if (t == 0) return 0;
        bool debug = false;

        for (size_t i = 3; i < params.size(); i += 2)
        {
            double component = params[i- 1];
            double start = params[i];
            debug |= std::abs(component) >= 0.99999;
            if (t >= start)
            {
                double proportion = (t - start) / (T - start);
                value += proportion * component;
                max += proportion;
            }
        }
        double retval = value / max;
#ifdef exprtk_enable_debugging
        std::cout << "mixin ";
        int i = 0;
        for (std::vector<double>::const_iterator it = params.begin(); it != params.end(); it++)
        {
            std::cout << (i++ == 0 ? "(" : ", ");
            std::cout << *it;
        }
        std::cout << ") = " << retval << ", max = " << max << std::endl;
#endif
        return retval;
    }

    virtual ~mixinfunction() {}
};

class FrequencyFunctionWaveFileOrGroup
{
public:
    virtual double Amplitude(double t, int32_t n) = 0;
    virtual ~FrequencyFunctionWaveFileOrGroup() {};
    virtual bool shouldCalculateForTime(const double& t)
    {
        return true;
    }
};

class FrequencyFunctionWaveFile : public FrequencyFunctionWaveFileOrGroup
{
public:
    static int nextid;
    int id = nextid++;

    channelfunction* thechannelfunction;
    mixinfunction themixinfunction;

    FrequencyFunctionWaveFile(const nlohmann::json j, const std::map<std::string, double>& constants, double channel, const headerdata& h, channelfunction* thechannelfunction, bool calculationOnly);
    FrequencyFunctionWaveFile(const FrequencyFunctionWaveFile& other);

    bool initialized;
    bool calculationOnly;
    double startTime; // don't process it before this time. optimization for Breaks2 file (json autogenerated from numbers)
    double endTime; // don't process it after this time. optimization for Breaks2
    bool everFiltered;
    exprtk::symbol_table<double> symbol_table_frequency;
    exprtk::symbol_table<double> symbol_table_pulse;
    exprtk::expression<double> expression_frequency;
    exprtk::expression<double> expression_pulse;

    void compile(const std::string& description, const std::string& expression_string, exprtk::symbol_table<double> symbol_table   /* invokes copy constructor */, exprtk::expression<double>& expression);

    std::string frequency, pulse;
    static std::string get_expression(const std::string& expression);
    static std::vector<std::string> get_missing_variables(exprtk::symbol_table<double> symbol_table, const std::string& expression);
    static double randomdouble();
    static double randombetween(double bottom, double top);
    static double sinorcos(double index, double arg);

    static void make_substitutions(std::string& input, const std::string& substitutions);
    static void replace_all(std::string& str, const std::string& from, const std::string& to);

    headerdata h;
    void initialize();
    double *t, *tprev, *n, *x, *xprev, *f;
    double *gradient, *gradientprev;
    double channelindex;

    std::map<std::string, double*> variables;
    std::map<std::string, double> _constants;

    double aLast;
    virtual ~FrequencyFunctionWaveFile();
    double Amplitude(double t, int32_t n);
    double Frequency();
    bool shouldCalculateForTime(const double& t);
};
