#pragma once
#include "headerdata.h"

class FrequencyFunctionWaveFileOrGroup
{
public:
    virtual double Amplitude(double t, int32_t n) = 0;
    virtual ~FrequencyFunctionWaveFileOrGroup() {};
    virtual bool shouldCalculateForTime(const double& t)
    {
        return true;
    }
};

class FrequencyFunctionWaveFile : public FrequencyFunctionWaveFileOrGroup
{
public:
    bool initialized;
    double startTime; // don't process it before this time. optimization for Breaks2 file (json autogenerated from numbers)
    double endTime; // don't process it after this time. optimization for Breaks2
    bool everFiltered;
    exprtk::symbol_table<double> symbol_table_frequency;
    exprtk::symbol_table<double> symbol_table_pulse;
    exprtk::expression<double> expression_frequency;
    exprtk::expression<double> expression_pulse;
    std::string frequency, pulse;
    static std::string get_expression(const std::string& expression);

    static double randomdouble();
    static double randombetween(double bottom, double top);
    static double sinorcos(double index, double arg);

    headerdata h;
    void initialize();
    double *t, *tprev, *n, *x, *xprev, *f;
    double *gradient, *gradientprev;
    double channelindex;

    static std::map<std::string, double*> variables;
    std::map<std::string, double> _constants;
    void parse_vars(const std::string& varsFile);

    double aLast;
    FrequencyFunctionWaveFile(const nlohmann::json j, const std::map<std::string, double>& constants, double channel, const headerdata& h);
    FrequencyFunctionWaveFile(const FrequencyFunctionWaveFile& other);
    virtual ~FrequencyFunctionWaveFile();
    double Amplitude(double t, int32_t n);
    double Frequency();
    bool shouldCalculateForTime(const double& t);
};
